# Use the official python image from Docker Hub
FROM python

# Set the working directory inside the container
WORKDIR /app

# Copy the application files from the host to the working directory in the container
COPY . /app

# Define the command to run the python file using python.
CMD [ "python", "rng.py"]